### ISSUE TITLE
Link on how to reproduce at bottom of README is broken

### ISSUE THREAD

**Issue by timfoyle** [didtheyvotein/edison#1]
Also, can you add the methodology used to collate the various `[state]_Precincts_Timeseries_Full.csv` files from the original source data? For example, the PA file looks like it has been built using timestamped json files of precinct-level cumulative votes from Edison. If these are still available can you link to the sources so people interested in reproducing your results can confirm the authenticity of the data.

The NYT, for example list PA results [here](https://www.nytimes.com/interactive/2020/11/03/us/elections/results-pennsylvania-president.html). This page serves a `president.json` file which includes (under keys ["races"][0]["precinct_metadata"]) a reference to a timestamped file of precinct-level cumulative results from Edison - e.g: https://static01.nyt.com/elections-assets/2020/data/api/2020-11-03/precincts/PAGeneralConcatenator-2020-11-26T01:42:09.611Z.json

Have you used a series of `[state]GeneralConcatenator-[timestamp].json` files to build your data set? If so, are the json files still available and where and where did you get the timestamps from?

Very much looking forward to repeating your work, but need to verify provenance of the data, thanks.

**Comment by didtheyvotein** [comment]
I added the code and fixed the link. However I've sworn off this style of analysis due to quality issues in the underlying data.
